# Generated by Django 4.2.23 on 2025-07-16 09:58

from django.db import migrations, models
import django.db.models.deletion
import parts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자동차 회사명')),
                ('is_imported', models.BooleanField(default=False, verbose_name='수입자동차 여부')),
            ],
            options={
                'verbose_name': '자동차 회사 관리',
                'verbose_name_plural': '자동차 회사 관리',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='차량 모델')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='parts.carmanufacturer', verbose_name='자동차 회사')),
            ],
            options={
                'verbose_name': '차량 모델',
                'verbose_name_plural': '차량 모델 관리',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('part_number', models.CharField(max_length=256, verbose_name='제품번호')),
                ('applicable_years', models.CharField(help_text='예: 2015-2018', max_length=50, verbose_name='연식')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='재고')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='가격')),
                ('description', models.TextField(blank=True, verbose_name='유의사항')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.carmodel', verbose_name='차량 모델')),
            ],
            options={
                'verbose_name': '부품',
                'verbose_name_plural': '부품 관리',
            },
        ),
        migrations.CreateModel(
            name='PartSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.CharField(choices=[('front', '전면'), ('rear', '후면'), ('side', '측면'), ('interior', '실내'), ('wheel', '중고순정휠'), ('underbody', '하체'), ('etc', '기타')], max_length=20, verbose_name='부품 카테고리1')),
                ('name', models.CharField(max_length=100, verbose_name='부품 카테고리2')),
            ],
            options={
                'verbose_name': '부품 카테고리',
                'verbose_name_plural': '부품 카테고리',
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=parts.models.PartImage.image_upload_path)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.partsubcategory', verbose_name='부품 카테고리'),
        ),
    ]
