# Generated by Django 4.2.23 on 2025-07-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(help_text='회사가 없다면 + 버튼을 눌러 추가해주세요.', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='parts.carmanufacturer', verbose_name='자동차 회사'),
        ),
        migrations.AlterField(
            model_name='part',
            name='car_model',
            field=models.ForeignKey(blank=True, help_text='차량 모델이 없다면 + 버튼을 눌러 추가해주세요.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.carmodel', verbose_name='차량 모델'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='0으로 입력 시 전화상담으로 표시', max_digits=10, null=True, verbose_name='가격'),
        ),
    ]
