# Generated by Django 4.2.23 on 2025-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_carmodel_manufacturer_alter_part_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsubcategory',
            name='parent_category',
            field=models.CharField(choices=[('front', '전면부품'), ('rear', '후면부품'), ('side', '측면부품'), ('interior', '실내부품'), ('wheel', '중고순정휠'), ('underbody', '하체부품'), ('etc', '기타부품')], max_length=20, verbose_name='부품 카테고리1'),
        ),
    ]
