# Generated by Django 4.2.23 on 2025-08-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_partsubcategory_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='세부 차종 이름')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='parts.carmodel', verbose_name='차량 모델')),
            ],
            options={
                'verbose_name': '세부 차종',
                'verbose_name_plural': '세부 차종 관리',
            },
        ),
    ]
