# Generated by Django 4.2.23 on 2025-08-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_carmodeldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='car_model_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.carmodeldetail', verbose_name='세부 차종'),
        ),
    ]
