# Generated by Django 4.2.23 on 2025-08-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_part_car_model_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='car_model_detail',
            field=models.ForeignKey(blank=True, help_text='세부 차종명이 없다면 + 버튼을 눌러 추가해주세요.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.carmodeldetail', verbose_name='세부 차종'),
        ),
    ]
