# Generated by Django 4.2.23 on 2025-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
