# Generated by Django 4.2.23 on 2025-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_notice_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_image',
            name='image',
            field=models.ImageField(help_text='이미지는 게시글 상단에 보여집니다.', upload_to='notices/images/', verbose_name='이미지'),
        ),
    ]
