# Generated by Django 4.2.23 on 2025-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_applied',
            field=models.BooleanField(default=False, verbose_name='재고 차감 완료'),
        ),
    ]
